/** Rich destination data for home search, charts, and detail panels (no login). */

export const DESTINATION_DETAILS = [
  {
    name: "Lalibela",
    region: "Amhara",
    price: "29,900 ETB",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1596423735880-5f2a689b903e?auto=format&fit=crop&w=1200&q=80",
    description: "UNESCO rock-hewn churches and Ethiopian Orthodox heritage. Compact town, walkable sites, strong cultural tourism infrastructure.",
    avgTempDry: "15–24°C",
    climateNote: "Highland climate: mild days, cool nights. Rainy season Jul–Sep; drier Oct–May.",
    bestMonths: "Oct – Mar",
    travelVolumeIndex: 92,
    lat: 12.0319,
    lng: 38.9806,
    distanceKm: 700,
    hotels: ["Roha Hotel", "Maribela Hotel", "Lal Hotel"],
  },
  {
    name: "Gondar",
    region: "Amhara",
    price: "21,900 ETB",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1526772662000-3f88f10405ff?q=80&w=1200",
    description: "The ‘Camelot of Africa’: Royal Enclosure castles, Debre Berhan Selassie church, and easy access to Simien Mountains staging.",
    avgTempDry: "16–26°C",
    climateNote: "Temperate highland pattern. Rain Jul–Sep. Pleasant outside rainy season.",
    bestMonths: "Oct – Jun",
    travelVolumeIndex: 88,
    lat: 12.6,
    lng: 37.4667,
    distanceKm: 730,
    hotels: ["Goha Hotel", "Haile Resort Gondar", "Florida International"],
  },
  {
    name: "Aksum",
    region: "Tigray",
    price: "24,900 ETB",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1589118949245-7d38baf380d6?auto=format&fit=crop&w=1200&q=80",
    description: "Ancient stelae field, church traditions, and deep historical significance on the northern circuit.",
    avgTempDry: "18–28°C",
    climateNote: "Warmer than Gondar. Plan around regional advisories and seasonal road conditions.",
    bestMonths: "Oct – Feb",
    travelVolumeIndex: 72,
    lat: 14.1211,
    lng: 38.7183,
    distanceKm: 1000,
    hotels: ["Yeha Hotel", "Sabean International", "Consular Hotel"],
  },
  {
    name: "Simien Mountains",
    region: "Amhara",
    price: "38,900 ETB",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80",
    description: "Dramatic escarpments, endemic wildlife (Gelada, Walia ibex), and multi-day trekking in Simien Mountains National Park.",
    avgTempDry: "10–20°C",
    climateNote: "Altitude-driven weather changes quickly. carry layers year-round.",
    bestMonths: "Oct – Mar",
    travelVolumeIndex: 78,
    lat: 13.2405,
    lng: 38.3577,
    distanceKm: 800,
    hotels: ["Simien Lodge", "Limalimo Lodge", "Camping Tents"],
  },
  {
    name: "Danakil Depression",
    region: "Afar",
    price: "45,900 ETB",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?q=80&w=1200",
    description: "Extreme landscapes: salt flats, active geology, and guided expeditions. Best as an organized tour.",
    avgTempDry: "35°C+",
    climateNote: "One of Earth’s hottest regions. Travel is highly seasonal and logistics-dependent.",
    bestMonths: "Nov – Mar",
    travelVolumeIndex: 55,
    lat: 14.2417,
    lng: 40.3,
    distanceKm: 1100,
    hotels: ["Mobile Campsites", "Hamad Ela Village", "Local Guesthouses"],
  },
  {
    name: "Lake Tana",
    region: "Amhara",
    price: "19,900 ETB",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?q=80&w=1200",
    description: "Island monasteries, birdlife, and boat culture near Bahir Dar — a relaxed complement to the northern route.",
    avgTempDry: "18–28°C",
    climateNote: "Generally stable outside heavy rains. Winds on the lake can affect schedules.",
    bestMonths: "Sep – Mar",
    travelVolumeIndex: 81,
    lat: 11.5,
    lng: 37.35,
    distanceKm: 560,
    hotels: ["Kuriftu Resort", "Blue Nile Resort", "Avanti Blue Nile"],
  },
  {
    name: "Hawassa",
    region: "Sidama",
    price: "17,900 ETB",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?q=80&w=1200",
    description: "Lakeside city with coffee country access, birding, and a calmer pace for Rift Valley stops.",
    avgTempDry: "16–27°C",
    climateNote: "Rift Valley pattern: two rainy seasons. Lake breezes moderate heat.",
    bestMonths: "Oct – Mar",
    travelVolumeIndex: 64,
    lat: 7.05,
    lng: 38.4667,
    distanceKm: 270,
    hotels: ["Haile Resort Hawassa", "Lewi Resort", "Central Hawassa Hotel"],
  },
  {
    name: "Bale Mountains",
    region: "Oromia",
    price: "34,900 ETB",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1519681393784-d120267933ba?q=80&w=1200",
    description: "Afro-alpine moorland, Ethiopian wolf habitat, and quieter trekking compared to the northern circuit.",
    avgTempDry: "8–18°C",
    climateNote: "Altitude-driven weather. Dry season offers best road access to high camps.",
    bestMonths: "Nov – Mar",
    travelVolumeIndex: 58,
    lat: 6.8833,
    lng: 39.6833,
    distanceKm: 400,
    hotels: ["Bale Mountain Lodge", "Dinsho Guesthouse", "Wabe Shebelle Hotel"],
    aliases: ["Bale", "Bale Mountains National Park"],
  },
  {
    name: "Bishoftu",
    region: "Oromia",
    price: "15,900 ETB",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
    description: "Crater lakes and lakeside lodges a short drive from Addis — ideal weekend escapes and birding.",
    avgTempDry: "16–26°C",
    climateNote: "Mild highland Rift fringe. Afternoon breezes on the lakes.",
    bestMonths: "Oct – May",
    travelVolumeIndex: 70,
    lat: 8.7522,
    lng: 38.9784,
    distanceKm: 45,
    hotels: ["Kuriftu Resort Bishoftu", "Liesak Resort", "Asham Africa Hotel"],
    aliases: ["Debre Zeyit", "Bushoftu"],
  },
  {
    name: "Lake Langano",
    region: "Oromia",
    price: "169 ETB",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1200&q=80",
    description: "Brown-sand Rift Valley lake with resorts, swimming, and watersports — a classic Rift Valley stop.",
    avgTempDry: "18–30°C",
    climateNote: "Warm days year-round. Check local water quality guidance before swimming.",
    bestMonths: "Oct – Mar",
    travelVolumeIndex: 62,
    lat: 7.3167,
    lng: 38.7833,
    distanceKm: 200,
    hotels: ["Sabana Beach Resort", "African Vacation Club", "Bishangari Lodge"],
    aliases: ["Langano"],
  },
  {
    name: "Wenchi Crater Lake",
    region: "Oromia",
    price: "189 ETB",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1200&q=80",
    description: "Dramatic crater lake reached by hike or horse; island monastery and community eco-tourism.",
    avgTempDry: "14–24°C",
    climateNote: "Cooler than the Rift floor. Mud on trails in Jul–Sep.",
    bestMonths: "Oct – May",
    travelVolumeIndex: 52,
    lat: 9.2167,
    lng: 37.2167,
    distanceKm: 155,
    hotels: ["Negash Lodge (Ambo)", "Eco-Lodges", "Community Homestays"],
    aliases: ["Wonchi", "Mount Wenchi"],
  },
  {
    name: "Arba Minch",
    region: "Southern Nations",
    price: "209 ETB",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
    description: "Gateway to Nechisar National Park — boat trips, hippos, and the famous ‘crocodile market’.",
    avgTempDry: "20–32°C",
    climateNote: "Warm Rift climate. Roads in the park can be tricky when wet.",
    bestMonths: "Jun – Feb",
    travelVolumeIndex: 60,
    lat: 6.0333,
    lng: 37.55,
    distanceKm: 450,
    hotels: ["Haile Resort Arba Minch", "Paradise Lodge", "Swaynes Hotel"],
    aliases: ["Forty Springs"],
  },
  {
    name: "Blue Nile Falls",
    region: "Amhara",
    price: "139 ETB",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
    description: "Tis Issat — one of Ethiopia’s great water spectacles near Bahir Dar; pair with Lake Tana.",
    avgTempDry: "18–29°C",
    climateNote: "Flow is highest after rains (roughly Jul–Sep). Smaller in dry months.",
    bestMonths: "Sep – Mar",
    travelVolumeIndex: 74,
    lat: 11.4964,
    lng: 37.6036,
    distanceKm: 580,
    hotels: ["Kuriftu Bahir Dar", "Blue Nile Resort", "Jacaranda Hotel"],
    aliases: ["Tis Issat", "Bahir Dar falls", "Blu Nalis Falls", "Blue Nile"],
  },
  {
    name: "Awash National Park",
    region: "Afar / Oromia",
    price: "199 ETB",
    rating: 4.4,
    image: "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?auto=format&fit=crop&w=1200&q=80",
    description: "Savanna wildlife, volcanic landscapes, and the Awash River gorge with waterfalls.",
    avgTempDry: "22–34°C",
    climateNote: "Hot and dry much of the year. Cooler mornings Dec–Feb.",
    bestMonths: "Nov – Mar",
    travelVolumeIndex: 48,
    lat: 9.0167,
    lng: 40.1667,
    distanceKm: 225,
    hotels: ["Awash Falls Lodge", "Doho Lodge", "Genet Hotel"],
    aliases: ["Awash Falls", "Awash"],
  },
  {
    name: "Addis Ababa",
    region: "Addis Ababa",
    price: "150 ETB",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=1200&q=80",
    description: "The diplomatic capital of Africa. Museums, vibrant markets, and high-altitude forest views.",
    avgTempDry: "16–25°C",
    climateNote: "Mild highland climate. Rainy Jun–Sep. Always carry a light jacket.",
    bestMonths: "Oct – May",
    travelVolumeIndex: 98,
    lat: 9.03,
    lng: 38.74,
    distanceKm: 0,
    hotels: ["Sheraton Addis", "Hilton Addis", "Skylight Hotel"],
    aliases: ["Addis", "Finfine"],
  },
  {
    name: "Harar",
    region: "Harari",
    price: "210 ETB",
    rating: 4.9,
    image: "https://images.pexels.com/photos/105809/pexels-photo-105809.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "The walled city of Jugol, spiritual heritage, and the unique Hyena feeding tradition.",
    avgTempDry: "18–28°C",
    climateNote: "Warm and dry. Historically a colorful trading hub.",
    bestMonths: "Oct – Feb",
    travelVolumeIndex: 68,
    lat: 9.3167,
    lng: 42.1167,
    distanceKm: 525,
    hotels: ["Heritage Plaza", "Rewda Guesthouse", "Grand Guesthouse"],
    aliases: ["Jugol", "Harer"],
  },
  {
    name: "Jimma",
    region: "Oromia",
    price: "180 ETB",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80",
    description: "The heart of coffee culture. Aba Jifar palace and lush tropical forests of Arabica birth.",
    avgTempDry: "17–28°C",
    climateNote: "Tropical highland climate. Very lush and green year-round.",
    bestMonths: "Nov – Mar",
    travelVolumeIndex: 56,
    lat: 7.6667,
    lng: 36.8333,
    distanceKm: 350,
    hotels: ["Central Jimma", "Honey Land Hotel", "Aba Jifar Hotel"],
    aliases: ["Jima"],
  },
  {
    name: "Adama",
    region: "Oromia",
    price: "140 ETB",
    rating: 4.4,
    image: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1200&q=80",
    description: "A bustling transportation hub. Famous for warm weather and proximity to the Rift Valley.",
    avgTempDry: "20–30°C",
    climateNote: "Warm Rift Valley fringe. Relatively dry compared to Addis.",
    bestMonths: "Sep – Jun",
    travelVolumeIndex: 75,
    lat: 8.5414,
    lng: 39.2689,
    distanceKm: 95,
    hotels: ["Canopy Hotel", "Adama German Hotel", "Executive Post Hotel"],
    aliases: ["Nazret", "Nazareth"],
  },
  {
    name: "Geralta Mountains",
    region: "Tigray",
    price: "280 ETB",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1454496522488-7a8e488e8606?auto=format&fit=crop&w=1200&q=80",
    description: "Dramatic sandstone cliffs housing some of the world's most inaccessible rock-hewn churches.",
    avgTempDry: "18–30°C",
    climateNote: "Semi-arid. Best for adventure seekers and climbers.",
    bestMonths: "Oct – Mar",
    travelVolumeIndex: 62,
    lat: 13.98,
    lng: 39.41,
    distanceKm: 900,
    hotels: ["Gheralta Lodge", "Korkor Lodge", "Agoro Lodge"],
    aliases: ["Gheralta", "Abuna Yemata Guh"],
  },
  {
    name: "Jinka",
    region: "Southern Nations",
    price: "260 ETB",
    rating: 4.7,
    image: "https://images.pexels.com/photos/4243048/pexels-photo-4243048.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Gateway to the Omo Valley and home to the South Omo Research Center.",
    avgTempDry: "20–32°C",
    climateNote: "Tropical savanna. Rains can impact road access.",
    bestMonths: "Jun – Mar",
    travelVolumeIndex: 59,
    lat: 5.78,
    lng: 36.65,
    distanceKm: 570,
    hotels: ["Eco-Omo Lodge", "Jinka Resort", "Nasa Hotel"],
    aliases: ["South Omo"],
  },
  {
    name: "Dire Dawa",
    region: "Dire Dawa",
    price: "170 ETB",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1593642532744-d377ab507dc8?auto=format&fit=crop&w=1200&q=80",
    description: "French-colonial architecture and traditional culture with vibrant spice markets.",
    avgTempDry: "22–35°C",
    climateNote: "Hot and dry. A pleasant stop between Addis and Harar.",
    bestMonths: "Oct – Feb",
    travelVolumeIndex: 65,
    lat: 9.6,
    lng: 41.85,
    distanceKm: 450,
    hotels: ["Samrat Hotel", "African Village", "Ras Hotel"],
    aliases: ["Dire"],
  },
  {
    name: "Semera",
    region: "Afar",
    price: "300 ETB",
    rating: 4.3,
    image: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80",
    description: "The capital of Afar. Staging point for Danakil and home to the Lucy museum.",
    avgTempDry: "25–42°C",
    climateNote: "Extreme desert heat. Only for the prepared traveler.",
    bestMonths: "Dec – Feb",
    travelVolumeIndex: 45,
    lat: 11.79,
    lng: 41.0,
    distanceKm: 590,
    hotels: ["Agda Hotel", "Kuriftu Semera", "Local Guesthouses"],
  },
  {
    name: "Gambela",
    region: "Gambela",
    price: "220 ETB",
    rating: 4.2,
    image: "https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&w=1200&q=80",
    description: "Vast wetlands and Baro River vistas. Home to unique Nilotic cultures.",
    avgTempDry: "24–38°C",
    climateNote: "Hot and humid. High seasonal rainfall.",
    bestMonths: "Nov – Jan",
    travelVolumeIndex: 38,
    lat: 8.25,
    lng: 34.58,
    distanceKm: 770,
    hotels: ["Grand Resort Gambela", "Baro Hotel", "Gambela Lodge"],
  },
  {
    name: "Dessie",
    region: "Amhara",
    price: "160 ETB",
    rating: 4.4,
    image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=1200&q=80",
    description: "Major highland city nestled in mountains. Gateway to the northern circuit.",
    avgTempDry: "15–25°C",
    climateNote: "Highland climate. Often misty and cool.",
    bestMonths: "Oct – Jun",
    travelVolumeIndex: 58,
    lat: 11.13,
    lng: 39.63,
    distanceKm: 400,
    hotels: ["Memhir Akalewold", "Tose Hotel", "Roha Hotel Dessie"],
  },
  {
    name: "Tiya",
    region: "Southern Nations",
    price: "120 ETB",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1508138221679-760a23a2285b?auto=format&fit=crop&w=1200&q=80",
    description: "UNESCO site featuring ancient megalithic stelae with unique carvings.",
    avgTempDry: "18–28°C",
    climateNote: "Mild. A great day trip from Addis Ababa.",
    bestMonths: "Year-round",
    travelVolumeIndex: 54,
    lat: 8.43,
    lng: 38.6,
    distanceKm: 90,
    hotels: ["Day Trip (Return to Addis)", "Local Guesthouses"],
  },
  {
    name: "Turmi",
    region: "Southern Nations",
    price: "270 ETB",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1200&q=80",
    description: "Central hub for the Hamer people. Witness bull-jumping and vibrant markets.",
    avgTempDry: "22–34°C",
    climateNote: "Warm savanna. Best visited in the drier months.",
    bestMonths: "Jun – Sep",
    travelVolumeIndex: 57,
    lat: 4.97,
    lng: 36.48,
    distanceKm: 800,
    hotels: ["Buska Lodge", "Turmi Lodge", "Evangadi Lodge"],
  },
  {
    name: "Negash",
    region: "Tigray",
    price: "190 ETB",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80",
    description: "First Muslim settlement in Africa. Home to Al-Nejashi mosque.",
    avgTempDry: "18–28°C",
    climateNote: "Arid highlands. Historically significant year-round.",
    bestMonths: "Oct – Mar",
    travelVolumeIndex: 42,
    lat: 13.88,
    lng: 39.6,
    distanceKm: 810,
    hotels: ["Negash Guesthouse", "Wukro Lodges"],
  },
  {
    name: "Mago National Park",
    region: "Southern Nations",
    price: "320 ETB",
    rating: 4.6,
    image: "https://images.pexels.com/photos/802112/pexels-photo-802112.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Home to the Mursi people and diverse savanna wildlife.",
    avgTempDry: "22–35°C",
    climateNote: "Hot and dusty. Roads can be impassable during heavy rains.",
    bestMonths: "Jun – Mar",
    travelVolumeIndex: 53,
    lat: 5.66,
    lng: 36.2,
    distanceKm: 780,
    hotels: ["Mobile Campsites", "Jinka Lodges"],
    aliases: ["Mango National Park", "Mango"],
  },
  {
    name: "Harenna Forest",
    region: "Oromia",
    price: "310 ETB",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=1200",
    description: "Natural high-canopy forest. Home to endemic Bale monkeys.",
    avgTempDry: "12–22°C",
    climateNote: "Cool and moist. Often shrouded in mist.",
    bestMonths: "Nov – Mar",
    travelVolumeIndex: 49,
    lat: 6.5,
    lng: 39.75,
    distanceKm: 450,
    hotels: ["Bale Mountain Lodge", "Harenna Eco-Camp"],
  },
  {
    name: "Yabelo",
    region: "Oromia",
    price: "240 ETB",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1547471080-7cb2cb6a5a36?auto=format&fit=crop&w=1200&q=80",
    description: "Heart of the Borana pastoralist culture and gateway to the Yabelo Wildlife Sanctuary.",
    avgTempDry: "20–30°C",
    climateNote: "Semi-arid and warm. Beautiful savanna landscapes.",
    bestMonths: "Sep – Mar",
    travelVolumeIndex: 40,
    lat: 4.88,
    lng: 38.08,
    distanceKm: 570,
    hotels: ["Yabelo Motel", "Local Lodges"],
  },
  {
    name: "Bahir Dar",
    region: "Amhara",
    price: "200 ETB",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?q=80&w=1200",
    description: "Palm-lined streets, Lake Tana monasteries, and the starting point for the Blue Nile falls.",
    avgTempDry: "16–28°C",
    climateNote: "Tropical savanna climate, cooled by the lake breeze.",
    bestMonths: "Sep – Mar",
    travelVolumeIndex: 85,
    lat: 11.59,
    lng: 37.39,
    distanceKm: 550,
    hotels: ["Kuriftu Resort", "Blue Nile Resort", "Jacaranda Hotel"],
    aliases: ["Bahirdar"]
  },
  {
    name: "Sof Omar Cave",
    region: "Oromia",
    price: "180 ETB",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=1200&q=80",
    description: "The longest cave system in Ethiopia, featuring a spectacular subterranean river.",
    avgTempDry: "22–32°C",
    climateNote: "Warm year-round. Check river levels before visiting.",
    bestMonths: "Nov – Mar",
    travelVolumeIndex: 35,
    lat: 6.9,
    lng: 40.8,
    distanceKm: 500,
    hotels: ["Robe Hotels", "Goba Wabe Shebelle"],
    aliases: ["Sof Umar", "Sof Umar Cafe", "Sof Omar"]
  }
];

export function matchesDestinationQuery(d, q) {
  if (d.name.toLowerCase().includes(q)) return true;
  if (d.region.toLowerCase().includes(q)) return true;
  if (`${d.name} ${d.region}`.toLowerCase().includes(q)) return true;
  const aliases = d.aliases || [];
  return aliases.some(
    (a) =>
      a.toLowerCase().includes(q) ||
      q.includes(a.toLowerCase()) ||
      a.toLowerCase() === q
  );
}

export function findDestinations(query) {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return DESTINATION_DETAILS.filter((d) => matchesDestinationQuery(d, q));
}

export function getDestinationByName(name) {
  const n = name.trim().toLowerCase();
  const byName = DESTINATION_DETAILS.find((d) => d.name.toLowerCase() === n);
  if (byName) return byName;
  return (
    DESTINATION_DETAILS.find((d) =>
      (d.aliases || []).some((a) => a.toLowerCase() === n)
    ) || null
  );
}

export function getDemoEconomics(d) {
  return {
    monthlyVisitors: Math.round(1600 + d.travelVolumeIndex * 210),
    avgSpendETB: Math.round(8800 + d.travelVolumeIndex * 420),
  };
}
